### ISSUE TITLE
[Request] Clickable classes in comment notes

### ISSUE THREAD

**Issue by gui679** [raideer/vscode-magento-toolbox#33]
![image](https://github.com/raideer/vscode-magento-toolbox/assets/15015995/b564a15e-b8c4-4ec0-bb34-02d5d56e2f24)
like these

**Comment by raideer** [comment]
You can right-click `$attribute` and click "Go to Type Definition". This will take you to the `AttributeInterface`.

**Comment by raideer** [comment]
Closing this. I'm currently working on a Language Server that will work much better than the current implementatio
